sudo: required
language: go
go_import_path: github.com/datanomix/kafka_exporter
env:
  global:
    - DOCKER_IMAGE_NAME=kafka_exporter
services:
  - docker
install: true
script:
  - make build
  - make docker
after_success:
  - make push
